Luciano/issue#1
lucianozapata/DD2480VT221 pull request #43
Opened 2022-01-29 11:46 UTC by lucianozapata

Started implementing #1 .

2022-01-29 12:33 UTC, persman96 requested changes

2022-01-29 12:33 UTC, persman96 commented on src/main/java/com/group24/decide/Decide.java
> +        Points[0] = new Datapoints(10,20);
These should be Points[1], Points[2] etc.

2022-01-29 16:41 UTC, persman96 commented on src/main/java/com/group24/decide/LIC.java
> -
I think you accidentally delete this.

2022-01-30 14:52 UTC, lucianozapata commented on src/main/java/com/group24/decide/LIC.java
> -
Yep, fixed it in next commit!

2022-01-30 15:30 UTC, persman96 approved these changes
Looks good!

2022-01-30 20:33 UTC, nikolim approved these changes
LGTM :+1:

2022-01-30 20:34 UTC, merged