Refact: refactor Decide class (issue#76)
lucianozapata/DD2480VT221 pull request #83
Opened 2022-02-01 20:57 UTC by avatar46

Added a constructor to Decide class. 
Changed the variables in the class. 
Added two methods calcCMV() and launch(). 
Added the Launcher class to replace Decide to serve as the main class. 
Refactored DecideTest class to be compatible with the Decide class.

2022-02-01 21:28 UTC, lucianozapata approved these changes
Looks very good! Well done!

2022-02-02 10:39 UTC, persman96 requested changes

2022-02-02 10:39 UTC, persman96 commented on src/main/java/com/group24/decide/Decide.java
> +        return true;
The function which determines this boolean signal should be called DECIDE() according to the specification.

2022-02-02 16:48 UTC, persman96 approved these changes
LGTM!

2022-02-02 16:48 UTC, merged